// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdrlihhhsewmiiwbwewi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcmxpaGhoc2V3bWlpd2J3ZXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTEwNTIsImV4cCI6MjA2OTcyNzA1Mn0.NGMww_KFIrSB1cb3xHyrxFhPoNJVl4VuBrjUuARx-_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});